export const MOVE_TO_CONSTRUCTOR = 'MOVE_TO_CONSTRUCTOR';
export const LOAD_INGREDIENTS = 'LOAD_INGREDIENTS';
export const SET_AS_DETAILED = 'SET_AS_DETAILED';
export const CLEAN_DETAILED = 'CLEAN_DETAILED';
export const GET_ORDER_NUMBER = 'GET_ORDER_NUMBER';