export const MOVE_TO_CONSTRUCTOR = 'MOVE_TO_CONSTRUCTOR';
export const LOAD_INGREDIENTS = 'LOAD_INGREDIENTS';
export const SET_AS_DETAILED = 'SET_AS_DETAILED';
export const CLEAN_DETAILED = 'CLEAN_DETAILED';
export const GET_ORDER_NUMBER = 'GET_ORDER_NUMBER';
export const TURN_ON_NOTICE = 'TURN_ON_NOTICE';
export const DELETE_FROM_CONSTRUCTOR = 'DELETE_FROM_CONSTRUCTOR';
export const MOVE_CONSTRUCTOR = 'MOVE_CONSTRUCTOR';