export const API_URL:'https://norma.nomoreparties.space/api/ingredients' = 'https://norma.nomoreparties.space/api/ingredients'; // ингредиенты
export const AUTH_ENDPOINT:'https://norma.nomoreparties.space/api/auth/login' = 'https://norma.nomoreparties.space/api/auth/login'; // эндпоинт для авторизации.
export const REGISTER_ENDPOINT:'https://norma.nomoreparties.space/api/auth/register' = 'https://norma.nomoreparties.space/api/auth/register'; // эндпоинт для регистрации пользователя.
export const LOGOUT_ENDPOINT:'https://norma.nomoreparties.space/api/auth/logout' = 'https://norma.nomoreparties.space/api/auth/logout'; // эндпоинт для выхода из системы.
export const TOKEN_ENDPOINT:'https://norma.nomoreparties.space/api/auth/token' = 'https://norma.nomoreparties.space/api/auth/token'; // эндпоинт обновления токена. 
export const PASS_RESET_ENDPOINT:'https://norma.nomoreparties.space/api/password-reset' = 'https://norma.nomoreparties.space/api/password-reset'; // сброс пароля (первый шаг)
export const PASS_RESET_STEP2_ENDPOINT:'https://norma.nomoreparties.space/api/password-reset/reset' = 'https://norma.nomoreparties.space/api/password-reset/reset'; // сброс пароля (второй шаг)
export const USER_INFORMATION_GET_ENDPOINT:'https://norma.nomoreparties.space/api/auth/user' = 'https://norma.nomoreparties.space/api/auth/user'; // получение данных пользователя в профиль, метод GET
export const USER_INFORMATION_PATCH_ENDPOINT:'https://norma.nomoreparties.space/api/auth/user' = 'https://norma.nomoreparties.space/api/auth/user'; // обновление данных пользователя, метод PATCH
export const WS_URL:'wss://norma.nomoreparties.space/orders' = 'wss://norma.nomoreparties.space/orders'; // эндпоинт для заказов, /all - для всех
export const ORDER_URL:'https://norma.nomoreparties.space/api/orders' = 'https://norma.nomoreparties.space/api/orders'; // получение заказа и номера заказа